# Assemble a Blockbench-friendly folder: every hand model together with the palette texture it
# uses, named the same so a model and its texture sit side by side.
#
# Blockbench can open the mod's own JSON files directly (they are plain Java item models), this
# folder just saves you hunting through the assets tree.
#
# ASCII-only on purpose: Windows PowerShell 5.1 reads non-ASCII .ps1 as GBK.

$root = Split-Path -Parent $PSScriptRoot
$modelsDir = Join-Path $root 'src\main\resources\assets\sephiria\models\item'
$texDir = Join-Path $root 'src\main\resources\assets\sephiria\textures\item'
$outDir = Join-Path $root 'blockbench'

New-Item -ItemType Directory -Force -Path $outDir | Out-Null

# every model that carries geometry, i.e. what is worth opening in Blockbench
$models = @(
    'sword_in_hand', 'shield_in_hand',
    'steel_greatsword_in_hand', 'dagger_in_hand', 'quarterstaff_in_hand',
    'katana_sheathed', 'katana_drawing', 'katana_in_hand',
    'crossbow_pulling_0', 'crossbow_pulling_1', 'crossbow_pulling_2', 'crossbow_loaded_in_hand',
    'colossal_crossbow_in_hand', 'default_sword_and_shield_in_hand', 'blade_in_hand'
)

$copied = 0
$missing = @()

foreach ($name in $models) {
    $modelPath = Join-Path $modelsDir ($name + '.json')
    if (-not (Test-Path $modelPath)) { $missing += $name; continue }

    Copy-Item $modelPath (Join-Path $outDir ($name + '.json')) -Force

    # the palette texture is whatever the model's "0" slot points at
    $json = [System.IO.File]::ReadAllText($modelPath, [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    $texRef = $json.textures.'0'
    if ($texRef) {
        $texName = ($texRef -split '/')[-1]
        $texPath = Join-Path $texDir ($texName + '.png')
        if (Test-Path $texPath) {
            Copy-Item $texPath (Join-Path $outDir ($texName + '.png')) -Force
        } else {
            $missing += ($name + ' texture: ' + $texName)
        }
    }
    $copied++
}

# the original sprites, useful to compare a model against the art it came from
foreach ($id in @('default_sword_and_shield', 'steel_greatsword', 'dagger', 'colossal_crossbow', 'blade', 'quarterstaff')) {
    $src = Join-Path $texDir ($id + '.png')
    if (Test-Path $src) { Copy-Item $src (Join-Path $outDir ('sprite_' + $id + '.png')) -Force }
}

$readme = @'
SEPHIRIA weapon models - for Blockbench
======================================

Each pair of files belongs together:
  <name>.json  the model (plain Minecraft Java item model, what the mod loads)
  <texture>.png  the palette texture, named EXACTLY as the model references it (e.g. shield_3d.png); Blockbench links a texture to a model by that name
  sprite_*.png the original 2D art the art-derived models were built from

How to open one
---------------
1. Blockbench -> File -> Open Model -> pick the .json
   (format "Java Block/Item Model" is detected automatically)
2. In the Textures panel click "Add Texture" and pick the matching .png
   The model is coloured by UVs into that palette, so it has to be the paired file.
3. Switch to the "Display" tab to see the in-hand transforms used by the game.

Notes
-----
- The "parent" field points at a base model inside the mod, so Blockbench cannot
  resolve it; that is expected and does not affect the geometry. The base models
  (models/item/weapon_3d.json etc.) only carry the hand display transforms.
- Which model shows up in game:
    sword_in_hand        standard sword+shield, main hand
    shield_in_hand       standard sword+shield, off hand
    katana_sheathed      blade item, idle
    katana_drawing       blade item, right click held (first half of the draw)
    katana_in_hand       blade item, right click held (fully drawn)
    crossbow_pulling_0/1/2  crossbow while winding up
    crossbow_loaded_in_hand crossbow when loaded
    colossal_crossbow_in_hand crossbow idle
- Editing: these files are GENERATED by tools/WeaponModels.java and
  tools/Voxelizer.java. If you tweak something here it will be overwritten the
  next time the generators run, so either tell me the change so it goes into the
  generator, or keep your edited copy under a different name.
- Regenerate this folder with: powershell -File tools\make-blockbench-bundle.ps1
'@

[IO.File]::WriteAllText((Join-Path $outDir 'README.txt'), $readme, (New-Object System.Text.UTF8Encoding($false)))

Write-Output ("models copied : " + $copied)
if ($missing.Count -gt 0) { Write-Output ("missing       : " + ($missing -join ', ')) }
Write-Output ("folder        : " + $outDir)
Get-ChildItem $outDir | Sort-Object Name | ForEach-Object { "  " + $_.Name }
